# Generated by Django 3.2.13 on 2022-05-09 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modelcv',
            options={'ordering': ['-created_at'], 'verbose_name': 'Модель', 'verbose_name_plural': 'Модели'},
        ),
        migrations.AlterModelOptions(
            name='requestcv',
            options={'ordering': ['-created_at'], 'verbose_name': 'Запрос', 'verbose_name_plural': 'Запросы'},
        ),
        migrations.AddField(
            model_name='modelcv',
            name='url',
            field=models.CharField(default='url', max_length=16),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='modelcv',
            name='description',
            field=models.TextField(),
        ),
    ]
