# Generated by Django 3.2.13 on 2022-05-14 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zoo', '0002_auto_20220509_1734'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestcv',
            old_name='response',
            new_name='output_img',
        ),
    ]
