# Generated by Django 3.2.13 on 2022-05-18 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoo', '0003_rename_response_requestcv_output_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestcv',
            name='output_img',
            field=models.ImageField(
                default=None,
                upload_to='images/%Y/%m/%d/'
            ),
        ),
    ]
